-- Weekly "media bias receipts" drafts, generated by the cron at
-- /api/cron/receipts and reviewed by you before posting (drafts mode).
-- Run this once in the Supabase SQL editor (prod project).

create table if not exists public.receipt_drafts (
  id          uuid primary key default gen_random_uuid(),
  content     text not null,
  status      text not null default 'draft',   -- draft | posted | discarded
  created_at  timestamptz not null default now()
);

-- Only the server-side service-role key (the cron) can touch this table.
-- RLS on + no public policy means the anon/browser key has no access.
alter table public.receipt_drafts enable row level security;
